### ISSUE TITLE
Cannot add multiple dogs with same name

### ISSUE THREAD

**Issue by ghost** [Kassi-Butler/ButlerKassi_CSCI2270_FinalProject#4]
When trying to add multiple dogs with same name either as lost or as found the post listing function says that dog already exists. In the Post-Conditions for editListing it says "Post-Conditions: Breed or information strings should be different for the Dog listing with matching name" so multiple dogs with same name are assumed to be possible.

**Comment by Kassi-Butler** [comment]
I wrote the code with the assumption that no dogs would have the same name for simplicity. However my documentation did not reflect that. Thank you
